config/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from django.contrib.flatpages import views
from delegate.views import DelegateCertificateView


urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),
    # User management
    url(r'^', include('common.urls')),
    url(r'^', include('orders.urls')),
    url(r'^', include('registration.urls')),
    url(r'^admin/ses/', include('django_ses.urls')),
    url(r'^delegate/', include('delegate.urls', namespace='delegate')),
    url(r'^organization/', include('organization.urls', namespace='organization')),
    url(r'^training-provider/', include('trainings.urls', namespace='training_provider')),
    url(r'^database-admin/', include('database_admin.urls', namespace='database_admin')),
    url(r'^database-super-admin/', include('database_super_admin.urls', namespace='database_super_admin')),
    url(r'^certificate/(?P<certificate_code>[^/]+)$', DelegateCertificateView.as_view(), name='delegate-certificate'),
]

# flatpages
urlpatterns += [
    url(r'^about/', include([
        url(r'^$', views.flatpage, {'url': '/about/'}, name='about'),
        url(r'^terms-and-conditions/$', views.flatpage, {'url': '/terms-and-conditions/'}, name='terms'),
        url(r'^privacy-policy/$', views.flatpage, {'url': '/privacy-policy/'}, name='privacy'),
        url(r'^service-level-agreement/$', views.flatpage, {'url': '/service-level-agreement/'}, name='agreement'),
    ])),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request),
        url(r'^403/$', default_views.permission_denied),
        url(r'^404/$', default_views.page_not_found),
        url(r'^500/$', default_views.server_error),
    ]

winda/common/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from common.views import HomeView, SendEmailNotificationRedirectView, SNSCallback, ArchiveRedirectView, \
    GenerateNotificationsRedirectView

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^sns-callback/$', SNSCallback.as_view(), name='sns_callback'),
    url(r'^send-email-notification/$', SendEmailNotificationRedirectView.as_view(), name='send_email_notification'),
    url(r'^archive/$', ArchiveRedirectView.as_view(), name='archive'),
    url(r'^generate-notifications/$', GenerateNotificationsRedirectView.as_view(), name='generate_notifications'),
]

winda/orders/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import url, include

from orders.views import CreditTemplateView, PurchaseCreditView, PurchaseConfirmView, OrderView, OrderDetailView, \
    EmailOrderDetailView, QuickPayCallback, OrderPaymentLinkView, TransactionView, TransactionDetailView

urlpatterns = [
    url(r'^training-provider/(?P<pk>\d+)/', include([
        url(r'^credits/$', CreditTemplateView.as_view(), name='credit'),
        url(r'^credits/purchase/$', PurchaseCreditView.as_view(), name='purchase_credit'),
        url(r'^credits/purchase-confirm/$', PurchaseConfirmView.as_view(), name='purchase_credit_confirm'),
        url(r'^orders/$', OrderView.as_view(), name='orders'),
        url(r'^orders/(?P<order_pk>\d+)/$', OrderDetailView.as_view(), name='order_detail'),
        url(r'^orders/(?P<order_pk>\d+)/email/$', EmailOrderDetailView.as_view(), name='order_email'),
        url(r'^orders/(?P<order_pk>\d+)/link/$', OrderPaymentLinkView.as_view(), name='order_link'),
        url(r'^transactions/$', TransactionView.as_view(), name='transactions'),
        url(r'^transactions/(?P<transaction_pk>\d+)/$', TransactionDetailView.as_view(), name='transaction_detail'),
    ])),

    url(r'^{}/$'.format(settings.QUICKPAY_CALLBACK_URL), QuickPayCallback.as_view(), name='quickpay_callback'),
]

winda/trainings/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include

from trainings.views import (
    TrainingProviderHomeView, UserListView, UserCreateView, UserUpdateView,
    CompanyProfileDetailView, UploadBatchListView, SingleUploadCreateView,
    BulkUploadCreateView, ViewUploadView, DownloadErrorsView
)

urlpatterns = [
    url(r'^(?P<pk>\d+)/', include([
        url(r'^$', TrainingProviderHomeView.as_view(), name='home'),
        url(r'^company-profile/$', CompanyProfileDetailView.as_view(), name='company_profile'),
        url(r'^uploads/', include([
            url(r'^$', UploadBatchListView.as_view(), name='uploads'),
            url(r'^new-single/$', SingleUploadCreateView.as_view(), name='single-upload'),
            url(r'^new-bulk/$', BulkUploadCreateView.as_view(), name='bulk-upload'),
            url(r'^(?P<batch_pk>\d+)/', include([
                url(r'^$', ViewUploadView.as_view(), name='view-upload'),
                url(r'^errors.csv$', DownloadErrorsView.as_view(), name='download-errors')
            ])),
        ])),
    ])),
    url(r'^users/(?P<user_id>\d+)/', include([
        url(r'^$', UserListView.as_view(), name='users'),
        url(r'^new/$', UserCreateView.as_view(), name='user_create'),
        url(r'^(?P<pk>\d+)/edit/$', UserUpdateView.as_view(), name='user_update'),
    ]))
]

winda/users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include


urlpatterns = [

]

winda/database_admin/models.py
from django.db import models

# Create your models here.

winda/organization/models.py
from django.db import models

# Create your models here.

winda/core/forms.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.contrib.auth import get_user_model
from django import forms
import reversion


class ModelForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        if self.request and self.request.user and self.request.user.is_authenticated():
            if self.instance.pk is None:
                self.instance.created_by = self.request.user
            else:
                self.instance.last_updated_by = self.request.user
        if reversion.is_active():
            if not reversion.get_user():
                system_user = get_user_model().objects.get(pk=settings.SYSTEM_USER_ID)
                reversion.set_user(system_user)
            if not self.instance.pk:
                reversion.set_comment('Added')
            elif self.changed_data:
                reversion.set_comment('Changed {}.'.format(', '.join(self.changed_data)))
        return super().save(commit)

winda/database_admin/forms.py
# -*- coding: utf-8 -*-
from collections import OrderedDict
import csv

from django import forms
from django.conf import settings
from django.db.models import Q, Count
from django.db import connection
from django.http import HttpResponse
from django.contrib.auth import get_user_model
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from common.forms import BaseFilterForm
from common.mixins import TrainingProviderCertificateFormMixin, DataBaseUserFormMixin
from common.models import EmailNotification, Country
from core.forms import ModelForm
from trainings.models import TrainingProvider, TrainingProviderCertificate
from courses.models import CourseProvider, Course
from database_admin.widgets import CustomFileInputWidget
from delegate.models import TrainingRecord
from orders.models import Order


User = get_user_model()


class TrainingProviderFilterForm(BaseFilterForm):
    FIELDS = OrderedDict([
        ('', ''),
        ('pk', 'ID'),
        ('name', _('name')),
        ('country', _('country')),
        ('postal_code', _('postal code')),
        ('is_active', _('is active')),
        ('accepted_at', _('accepted at')),
    ])


class TrainingProviderForm(ModelForm):
    class Meta:
        model = TrainingProvider
        fields = ('name', 'address_1', 'address_2', 'city', 'postal_code', 'country', 'is_active')
        required_fields = ('name', 'address_1', 'city', 'postal_code', 'country')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.required_fields:
            self.fields[field].required = True


class CoursesFilterForm(BaseFilterForm):
    FIELDS = OrderedDict([
        ('', ''),
        ('code', _('Code')),
        ('title', _('Title')),
        ('course_type', _('Course Type')),
        ('validity_months', _('Validity Period (Months)')),
    ])


class CertificatesFilterForm(BaseFilterForm):
    FIELDS = OrderedDict([
        ('', ''),
        ('certificate_number', _('Certificate number')),
        ('valid_from', _('Valid from')),
        ('valid_until', _('Valid until')),
        ('certificate_file', _('Certificate file')),
        ('is_deleted', _('Is Archived'))
    ])


class TrainingProviderCertificateForm(TrainingProviderCertificateFormMixin, ModelForm):
    valid_from = forms.DateField(widget=forms.DateInput(format=settings.FORMS_DATE_FORMAT),
                                 input_formats=settings.DATE_INPUT_FORMATS,
                                 label=_('Valid From'))
    valid_until = forms.DateField(widget=forms.DateInput(format=settings.FORMS_DATE_FORMAT),
                                  input_formats=settings.DATE_INPUT_FORMATS,
                                  label=_('Valid Until'))

    class Meta(TrainingProviderCertificateFormMixin.Meta):
        model = TrainingProviderCertificate
        fields = ('certificate_number', 'certificate_file', 'valid_until', 'valid_from', 'is_deleted')
        labels = {
            'certificate_file': _('certificate PDF'),
            'is_deleted': _('Is Archived'),
        }
        widgets = {
            'certificate_file': CustomFileInputWidget
        }


class AccreditationFilterForm(BaseFilterForm):

    FIELDS = OrderedDict([
            ('', ''),
            ('course__code', _('Code')),
            ('course__title', _('Course Title')),
            ('valid_from', _('Valid From')),
            ('valid_until', _('Valid Until')),
            ('is_deleted', _('Is Archived'))
        ])


class AccreditationForm(ModelForm):
    error_messages = {
        'future_valid_from': _('Date must be in the past.'),
        'past_valid_until': _('Date must be in the future.'),
        'valid_until_not_correct': _('Valid Until date must be after Valid From date.'),
    }
    course = forms.ModelChoiceField(queryset=Course.objects.all().order_by('code'), label=_('Course'))
    valid_from = forms.DateField(widget=forms.DateInput(format=settings.FORMS_DATE_FORMAT),
                                 input_formats=settings.DATE_INPUT_FORMATS,
                                 label=_('Valid From'))
    valid_until = forms.DateField(widget=forms.DateInput(format=settings.FORMS_DATE_FORMAT),
                                  input_formats=settings.DATE_INPUT_FORMATS,
                                  label=_('Valid Until'))

    class Meta:
        model = CourseProvider
        fields = ('course', 'valid_from', 'valid_until', 'is_deleted')
        labels = {
            'is_deleted': _('Is Archived'),
        }

    def clean_valid_from(self):
        valid_from = self.cleaned_data['valid_from']
        if valid_from >= timezone.now().date():
            raise forms.ValidationError(self.error_messages['future_valid_from'])
        return valid_from

    def clean_valid_until(self):
        valid_until = self.cleaned_data['valid_until']
        if valid_until <= timezone.now().date():
            raise forms.ValidationError(self.error_messages['past_valid_until'])
        return valid_until

    def clean(self):
        cd = super().clean()
        if self.errors:
            return cd
        if cd['valid_until'] <= cd['valid_from']:
            return self.add_error(None, self.error_messages['valid_until_not_correct'])
        return cd


class BaseReportForm(forms.Form):
    error_messages = {
        'date_until_not_correct': _('Date Until must be after Date From.'),
    }
    date_from = forms.DateField(widget=forms.DateInput(format=settings.FORMS_DATE_FORMAT),
                                input_formats=settings.DATE_INPUT_FORMATS,
                                label=_('Date From'))
    date_until = forms.DateField(widget=forms.DateInput(format=settings.FORMS_DATE_FORMAT),
                                 input_formats=settings.DATE_INPUT_FORMATS,
                                 label=_('Date Until'))

    def clean(self):
        cleaned_data = super().clean()
        if self.errors:
            return cleaned_data
        if cleaned_data['date_until'] <= cleaned_data['date_from']:
            return self.add_error(None, self.error_messages['date_until_not_correct'])
        return cleaned_data


class CSVGenerationMixin(object):

    filename = 'search_report_{}.csv'
    header = [_('Organisation domain'), _('Count')]

    def save(self):
        response = HttpResponse(content_type='text/csv')
        date = timezone.now().strftime(settings.TEMPLATE_DATE_FORMAT)
        filename = self.filename.format(date)
        response['Content-Disposition'] = 'attachment;filename={0}'.format(filename)
        writer = csv.writer(response)
        writer.writerow(self.header)
        self.write_rows(writer)
        return response

    def write_rows(self, writer):
        return writer


class TrainingRecordReportForm(CSVGenerationMixin, BaseReportForm):
    training_provider = forms.ModelChoiceField(queryset=TrainingProvider.objects.all().order_by('name'),
                                               label=_('Training Provider'), required=False)
    course = forms.ModelChoiceField(queryset=Course.objects.all().order_by('title'), label=_('Course'), required=False)

    filename = 'training_record_report.csv'
    header = [_('Training Record ID'), _('WINDA ID'), _('Delegate First Name'), _('Delegate Last Name'),
        _('Delegate Email'), _('Course Code'), _('Course Name'), _('Country'), _('Training Provider ID'),
        _('Training Provider Name'), _('Created At'), _('Completed On'), _('Valid From'), _('Valid Until')]

    def write_rows(self, writer):
        date_from = self.cleaned_data['date_from']
        date_until = self.cleaned_data['date_until']
        t_records = TrainingRecord.objects.filter(Q(created__lte=date_until) & Q(created__gte=date_from))
        t_records = t_records.select_related('delegate', 'training_provider', 'course', 'country')
        course = self.cleaned_data['course']
        training_provider = self.cleaned_data['training_provider']
        if training_provider:
            t_records = t_records.filter(training_provider_id=training_provider.id)
        if course:
            t_records = t_records.filter(course_id=course.id)

        for record in t_records.iterator():
            writer.writerow([
                record.id,
                record.delegate.delegate_id,
                record.delegate.first_name,
                record.delegate.last_name,
                record.delegate.email,
                record.course.code,
                record.course.title,
                record.country.name,
                record.training_provider_id,
                record.training_provider.name,
                record.created.strftime(settings.REPORTS_DATE_FORMAT),
                record.completed_on.strftime(settings.REPORTS_DATE_FORMAT),
                record.valid_from.strftime(settings.REPORTS_DATE_FORMAT),
                record.valid_until.strftime(settings.REPORTS_DATE_FORMAT)
            ])


class SearchReportForm(CSVGenerationMixin, BaseReportForm):

    filename = 'search_report_{}.csv'
    header = [_('Organisation domain'), _('Count')]

    def write_rows(self, writer):
        date_from = self.cleaned_data['date_from']
        date_until = self.cleaned_data['date_until']
        cursor = connection.cursor()
        # Count domains occurencies in user emails
        cursor.execute('SELECT substring_index(users_user.email, "@", -1), COUNT(*) '+
                       'FROM delegate_search INNER JOIN users_user ON (delegate_search.created_by_id=users_user.id)'+
                       ' where (delegate_search.created <= Date(%s) and delegate_search.created >=Date(%s)) '+
                       'GROUP BY substring_index(users_user.email, "@", -1) '+
                       'ORDER BY COUNT(*) DESC;', [date_until, date_from])
        searches = cursor.fetchall()
        for search in searches:
            writer.writerow([search[0], search[1]])
        return writer

winda/core/views.py
# -*- coding: utf-8 -*-
from django.views import generic
from reversion.views import RevisionMixin

class CreateView(RevisionMixin, generic.CreateView):
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


class UpdateView(RevisionMixin, generic.UpdateView):
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

winda/templates/database_admin/accreditation_change_history.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block title %}Winda Database Admin{% endblock title %}

{% block breadcrumb %}
    {{ block.super }}
    {{block.super}}
    <li><a href="{% url 'database_admin:training_providers' %}">{% trans 'Training Providers' %}</a></li>
    <li><a href="{% url 'database_admin:training_provider_detail' pk=provider.pk %}">{{provider.name|capfirst}}</a></li>
    <li><a href="{% url 'database_admin:training_provider_accreditations' provider.pk %}">{% trans 'Accreditations' %}</a></li>
    <li><a href="{% url 'database_admin:training_provider_accreditations_update' parent_pk=provider.pk pk=object.pk %}">{% trans 'Accreditation #' %}{{object.pk}}</a></li>
    <li>{% trans 'Change History' %}</li>
{% endblock %}
{% block content %}
    <h2 class="text-center">{% trans 'Change History' %}</h2>

    <table id="change_history" class="display responsive nowrap dataTable no-footer dtr-inline">
        <thead><tr>
            {% for title in form.FIELDS.values %}
                <th>{{ title|title }}</th>
            {% endfor %}
        </tr></thead>
        <tbody></tbody>
    </table>
{% endblock content %}

winda/templates/database_admin/course_create.html
{% extends "database_admin/course_edit.html" %}
{% load i18n %}

winda/templates/database_admin/mailout.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block title %}{% blocktrans %}Winda Database Admin - Mailout{% endblocktrans %}{% endblock title %}


{% block breadcrumb %}
    {{ block.super }}
    <li>{% trans 'Mailout' %}</li>
{% endblock %}

{% block content %}
<div class="wrapper-form">
    <h2 class="text-center">
        {% trans 'Mailout' %}
    </h2>

{{ form.non_field_errors }}
<form class="form-horizontal mailout-form" method="post">
    {% csrf_token %}
    <fieldset>
        <div class="form-group row">
            <label class="col-sm-3 control-label">{% trans 'From' %}</label>
            <div class="col-sm-9"><div class="form-control no-binput">{{ default_from_email }}</div></div>
        </div>

        <div class="form-group row">
            <label class="col-sm-3 control-label" for="{{ form.subject.id_for_label }}">{{ form.subject.label|capfirst }}</label>
            <div class="col-sm-9">
                <div class="row">
                        <div class="col-sm-2">
                            <div class="no-binput">
                                {{ prefix }}
                            </div>
                        </div>
                        <div class="col-sm-10">
                            {% render_field form.subject class='form-control' placeholder=form.subject.label|capfirst %}
                            <div class="errors">{{ form.subject.errors }}</div>
                        </div>
                </div>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-3 control-label" for="{{ form.body.id_for_label }}">{{ form.body.label|capfirst }}</label>
            <div class="col-sm-9">
                <div class="helper">{% trans 'Hi' %} {User.FirstName} {User.LastName},</div>
                {% render_field form.body class='form-control' placeholder=form.body.label|capfirst %}
                <div class="errors">{{ form.body.errors }}</div>
                <div class="helper">{% trans 'Regards' %},
                <p></p>
                {% trans 'The WINDA Team' %}</div>
            </div>
        </div>
        <hr>
        <div class="form-group row">
            <label class="col-sm-3 control-label" for="{{ form.role.id_for_label }}">{{ form.role.label|capfirst }}</label>
            <div class="col-sm-9">
                {% for radio in form.role %}
                    <div class="checkbox">
                        <label>{{ radio.tag }} <span class="check"></span> {{ radio.choice_label }}</label>
                    </div>
                {% endfor %}
            </div>

            <div class="col-sm-3"></div>
            <div class="col-sm-9">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="checkbox">
                            <label>{% render_field form.filter_by_country %}<span class="check"></span> {{ form.filter_by_country.label }}</label>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        {% render_field form.country class='form-control' placeholder=form.country.label|capfirst %}
                        <div class="errors">{{ form.country.errors }}</div>
                    </div>
                </div>
                <br>
            </div>
        </div>

        <hr>
        <div class="form-group row">
            <div class="col-sm-3"></div>
            <div class="col-sm-9">
                <div class="checkbox">
                    <label>{% render_field form.filter_by_course %}<span class="check"></span> {{ form.filter_by_course.label }}</label>
                    <div class="errors">{{ form.role.errors }}</div>
                </div>
            </div>
        </div>
        <div class="form-group row disabled">
            <label class="col-sm-3 control-label" for="{{ form.training_provider.id_for_label }}">{{ form.training_provider.label|capfirst }}</label>
            <div class="col-sm-9">
                {% render_field form.training_provider class='form-control' placeholder=form.training_provider.label|capfirst %}
                <div class="errors">{{ form.training_provider.errors }}</div>
                <p></p>
            </div>
            <label class="col-sm-3 control-label" for="{{ form.course.id_for_label }}">{{ form.course.label|capfirst }}</label>
            <div class="col-sm-9">
                {% render_field form.course class='form-control' placeholder=form.course.label|capfirst %}
                <p></p>
            </div>
        </div>
        <div class="form-group row disabled">
            <label class="col-sm-3 control-label">{% trans 'Сourse completion was between' %}</label>
            <div class="col-sm-9">
                <div class="helper">{% trans 'Сourse completion was between' %}</div>
                <div class="course-completion ">
                    <div class="course-date-wraper">
                    <label for="id_date_from">Date From</label>
                        <span class="input-group date" class="date-end">
                            {% render_field form.completed_on_start class='form-control' placeholder='- - -' %}
                            <span style="" class="input-group-addon">
                                <span class="icon icon-btn_calendar"></span>
                            </span>
                        </span>
                        <div class="errors">{{ form.completed_on_start.errors }}</div>
                    </div>
                    <div class="course-date-wraper">
                    <label for="id_date_until">Date Until</label>
                        <span class="input-group date" class="date-end">
                            {% render_field form.completed_on_end class='form-control' placeholder='- - -' %}
                            <span style="" class="input-group-addon">
                                <span class="icon icon-btn_calendar"></span>
                            </span>
                        </span>
                        <div class="errors">{{ form.completed_on_end.errors }}</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-3"></div>
            <div class="col-sm-9">
                <div class="errors">{{ form.filter_by_course.errors }}</div>
            </div>
        </div>
    </fieldset>
    <div class="text-center">
        <button id="send-mailout" class="btn btn-primary btn-lg text-uppercase">{% trans 'Send Mailout' %}</button>
    </div>
</form>
</div>
{% endblock content %}

winda/templates/database_admin/training_providers_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block title %}Winda Database Admin{% endblock title %}

{% block content %}
    <h2 class="text-center">{{ object.name|title }}</h2>

    <ul class="list-menu-home">
        <li>
            <a href="{% url 'training_provider:company_profile' object.pk %}">
               <figure>
                    <div class="icon-wrapper"><span class="icon icon-ic_titles_view_profile"></span></div>
                    <figcaption>
                        <h4>{% trans 'View Profile'|title %}</h4>
                        <small>{% trans 'View training provider profile' %}</small>
                    </figcaption>
                </figure>
            </a>
        </li>
        <li>
            <a href="{% url 'database_admin:training_provider_update' object.pk %}">
               <figure>
                    <div class="icon-wrapper"><span class="icon icon-ic_titles_edit_profile"></span></div>
                    <figcaption>
                        <h4>{% trans 'Edit Profile'|title %}</h4>
                        <small>{% trans 'Edit training provider profile' %}</small>
                    </figcaption>
                </figure>
            </a>
        </li>
        <li>
            <a href="#">
               <figure>
                    <div class="icon-wrapper"><span class="icon icon-ic_titles_users"></span></div>
                    <figcaption>
                        <h4>{% trans 'Users'|title %}</h4>
                        <small>{% trans 'Manage training provider users' %}</small>
                    </figcaption>
                </figure>
            </a>
        </li>
        <li>
            <a href="{% url 'training_provider:uploads' pk=object.pk %}">
               <figure>
                    <div class="icon-wrapper"><span class="icon icon-ic_titles_uploads"></span></div>
                    <figcaption>
                        <h4>{% trans 'Uploads'|title %}</h4>
                        <small>{% trans 'Manage uploads' %}</small>
                    </figcaption>
                </figure>
            </a>
        </li>
        <li>
            <a href="{% url 'database_admin:training_provider_accreditations' parent_pk=object.pk%}">
               <figure>
                    <div class="icon-wrapper"><span class="icon icon-ic_titles_accreditations"></span></div>
                    <figcaption>
                        <h4>{% trans 'Accreditations'|title %}</h4>
                        <small>{% trans 'Manage course accreditations' %}</small>
                    </figcaption>
                </figure>
            </a>
        </li>
        <li>
            <a href="{% url 'database_admin:training_provider_certifications' parent_pk=object.pk%}">
               <figure>
                    <div class="icon-wrapper"><span class="icon icon-ic_titles_certifications"></span></div>
                    <figcaption>
                        <h4>{% trans 'Certifications'|title %}</h4>
                        <small>{% trans 'Manage certificates' %}</small>
                    </figcaption>
                </figure>
            </a>
        </li>
        <li>
            <a href="{% url 'orders' object.pk %}">
               <figure>
                    <div class="icon-wrapper"><span class="icon icon-ic_titles_orders"></span></div>
                    <figcaption>
                        <h4>{% trans 'Orders'|title %}</h4>
                        <small>{% trans 'View orders' %}</small>
                    </figcaption>
                </figure>
            </a>
        </li>
        <li>
            <a href="{% url 'transactions' object.pk %}">
               <figure>
                    <div class="icon-wrapper">
                        <span class="icon icon-ic_titles_transactions"></span>
                    </div>
                    <figcaption>
                        <h4>{% trans 'Transactions'|title %}</h4>
                        <small>{% trans 'View transactions' %}</small>
                    </figcaption>
                </figure>
            </a>
        </li>
        <li>
            <a href="{% url 'database_admin:training_provider_award_credits' pk=object.pk %}">
               <figure>
                    <div class="icon-wrapper"><span class="icon icon-ic_titles_credits"></span></div>
                    <figcaption>
                        <h4>{% trans 'Award Credits'|title %}</h4>
                        <small>{% trans 'Add/subtract credits' %}</small>
                    </figcaption>
                </figure>
            </a>
        </li>
    </ul>
{% endblock content %}

{% block breadcrumb %}
    {{ block.super }}
    <li><a href="{% url 'database_admin:training_providers' %}">{% trans 'training providers'|title %}</a></li>
    <li>{{ object.name|title }}</li>
{% endblock %}

winda/templates/database_admin/users_change_history.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block title %}{% blocktrans %}Winda Database Admin - Change History{% endblocktrans %}{% endblock title %}

{% block breadcrumb %}
    {{block.super}}
    <li><a href="{% url 'database_admin:users' %}">{% trans 'Users' %}</a></li>
    <li><a href="{% url 'database_admin:user_detail' object.pk %}">{{ object.get_full_name }}</a></li>
    <li>{% trans 'Change History' %}</li>
{% endblock %}

{% block content %}
    <h2 class="text-center">{% trans 'Change History' %}</h2>
    <table id="change_history" class="display responsive nowrap dataTable no-footer dtr-inline">
        <thead><tr>
            {% for title in form.FIELDS.values %}
                <th>{{ title }}</th>
            {% endfor %}
        </tr></thead>
        <tbody></tbody>
    </table>
{% endblock content %}