config/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from django.contrib.flatpages import views
from delegate.views import DelegateCertificateView


urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),
    # User management
    url(r'^', include('common.urls')),
    url(r'^', include('orders.urls')),
    url(r'^', include('registration.urls')),
    url(r'^admin/ses/', include('django_ses.urls')),
    url(r'^delegate/', include('delegate.urls', namespace='delegate')),
    url(r'^organization/', include('organization.urls', namespace='organization')),
    url(r'^training-provider/', include('trainings.urls', namespace='training_provider')),
    url(r'^database-admin/', include('database_admin.urls', namespace='database_admin')),
    url(r'^database-super-admin/', include('database_super_admin.urls', namespace='database_super_admin')),
    url(r'^certificate/(?P<certificate_code>[^/]+)$', DelegateCertificateView.as_view(), name='delegate-certificate'),
]

# flatpages
urlpatterns += [
    url(r'^about/', include([
        url(r'^$', views.flatpage, {'url': '/about/'}, name='about'),
        url(r'^terms-and-conditions/$', views.flatpage, {'url': '/terms-and-conditions/'}, name='terms'),
        url(r'^privacy-policy/$', views.flatpage, {'url': '/privacy-policy/'}, name='privacy'),
        url(r'^service-level-agreement/$', views.flatpage, {'url': '/service-level-agreement/'}, name='agreement'),
    ])),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request),
        url(r'^403/$', default_views.permission_denied),
        url(r'^404/$', default_views.page_not_found),
        url(r'^500/$', default_views.server_error),
    ]

winda/common/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from common.views import HomeView, SendEmailNotificationRedirectView, SNSCallback, ArchiveRedirectView, \
    GenerateNotificationsRedirectView

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^sns-callback/$', SNSCallback.as_view(), name='sns_callback'),
    url(r'^send-email-notification/$', SendEmailNotificationRedirectView.as_view(), name='send_email_notification'),
    url(r'^archive/$', ArchiveRedirectView.as_view(), name='archive'),
    url(r'^generate-notifications/$', GenerateNotificationsRedirectView.as_view(), name='generate_notifications'),
]

winda/database_admin/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include

from database_admin.views import (
    CoursesListView, CourseUpdateView, TrainingProviderListView, TrainingProviderCreateView,
    TrainingProviderDetailView, TrainingProviderUpdateView, DatabaseAdminHomeView, CourseCreateView,
    CertificatesListView, CertificateCreateView, CertificateUpdateView, AccreditationListView,
    AccreditationCreateView, AccreditationUpdateView, DatabaseAdminAwardCreditView, DatabaseAdminReportsView,
    TrainingRecordReportView, SearchReportView, PaymentReportView, TrainingStatisticsReportView,
    DatabaseGrowthReportView, NotificationHistory, MailoutCreateView, TrainingProviderChangeHistoryView,
    CourseChangeHistoryView, CertificateChangeHistoryView, AccreditationChangeHistoryView, UsersChangeHistoryView,
    UserListView, UserDetailView)

urlpatterns = [
    url(r'^$', DatabaseAdminHomeView.as_view(), name='home'),
    url(r'^reports/', include([
            url(r'^$', DatabaseAdminReportsView.as_view(), name='reports'),
            url(r'^search_report/$', SearchReportView.as_view(), name='search_report'),
            url(r'^payment_report/$', PaymentReportView.as_view(), name='payment_report'),
            url(r'^training_record_report/$', TrainingRecordReportView.as_view(), name='training_record_report'),
            url(r'^training_statistics_report/$', TrainingStatisticsReportView.as_view(), name='training_statistics_report'),
            url(r'^database_growth_report/$', DatabaseGrowthReportView.as_view(), name='database_growth_report'),
        ])
    ),
    url(r'^courses/$', CoursesListView.as_view(), name='courses'),
    url(r'^courses/new$', CourseCreateView.as_view(), name='course_create'),
    url(r'^courses/(?P<pk>[\w]+)$', CourseUpdateView.as_view(), name='course_edit'),
    url(r'^courses/(?P<pk>[\w]+)/change-history/$', CourseChangeHistoryView.as_view(), name='course_change_history'),
    url(r'^training-providers/', include([
        url(r'^$', TrainingProviderListView.as_view(), name='training_providers'),
        url(r'^new/$', TrainingProviderCreateView.as_view(), name='training_provider_create'),
        url(r'^(?P<pk>\d+)/$', TrainingProviderDetailView.as_view(), name='training_provider_detail'),
        url(r'^(?P<pk>\d+)/change-history/$', TrainingProviderChangeHistoryView.as_view(), name='training_provider_history'),
        url(r'^(?P<pk>\d+)/edit/$', TrainingProviderUpdateView.as_view(), name='training_provider_update'),
        url(r'^(?P<pk>\d+)/award-credits/$', DatabaseAdminAwardCreditView.as_view(), name='training_provider_award_credits'),
        url(r'^(?P<parent_pk>\d+)/certifications/', include([
            url(r'^$', CertificatesListView.as_view(), name='training_provider_certifications'),
            url(r'^new/$', CertificateCreateView.as_view(), name='training_provider_certifications_create'),
            url(r'^(?P<pk>\d+)/$', CertificateUpdateView.as_view(), name='training_provider_certification_update'),
            url(r'^(?P<pk>\d+)/change-history/$', CertificateChangeHistoryView.as_view(), name='certification_change_history'),
        ])),
        url(r'^(?P<parent_pk>\d+)/accreditations/', include([
            url(r'^$', AccreditationListView.as_view(), name='training_provider_accreditations'),
            url(r'^new/$', AccreditationCreateView.as_view(), name='training_provider_accreditations_create'),
            url(r'^(?P<pk>\d+)/$', AccreditationUpdateView.as_view(), name='training_provider_accreditations_update'),
            url(r'^(?P<pk>\d+)/change-history/$', AccreditationChangeHistoryView.as_view(), name='accreditations_change_history'),
        ]))
    ])),
    url(r'^users/', include([
        url(r'^$', UserListView.as_view(), name='users'),
        url(r'^(?P<pk>\d+)/$', UserDetailView.as_view(), name='user_detail'),
        url(r'^(?P<pk>\d+)/notification-history/$', NotificationHistory.as_view(), name='notification_history'),
        url(r'^(?P<pk>\d+)/change-history/$', UsersChangeHistoryView.as_view(), name='user_change_history'),
    ])),
    url(r'^mailout/$', MailoutCreateView.as_view(), name='mailout'),
]

winda/orders/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import url, include

from orders.views import CreditTemplateView, PurchaseCreditView, PurchaseConfirmView, OrderView, OrderDetailView, \
    EmailOrderDetailView, QuickPayCallback, OrderPaymentLinkView, TransactionView, TransactionDetailView

urlpatterns = [
    url(r'^training-provider/(?P<pk>\d+)/', include([
        url(r'^credits/$', CreditTemplateView.as_view(), name='credit'),
        url(r'^credits/purchase/$', PurchaseCreditView.as_view(), name='purchase_credit'),
        url(r'^credits/purchase-confirm/$', PurchaseConfirmView.as_view(), name='purchase_credit_confirm'),
        url(r'^orders/$', OrderView.as_view(), name='orders'),
        url(r'^orders/(?P<order_pk>\d+)/$', OrderDetailView.as_view(), name='order_detail'),
        url(r'^orders/(?P<order_pk>\d+)/email/$', EmailOrderDetailView.as_view(), name='order_email'),
        url(r'^orders/(?P<order_pk>\d+)/link/$', OrderPaymentLinkView.as_view(), name='order_link'),
        url(r'^transactions/$', TransactionView.as_view(), name='transactions'),
        url(r'^transactions/(?P<transaction_pk>\d+)/$', TransactionDetailView.as_view(), name='transaction_detail'),
    ])),

    url(r'^{}/$'.format(settings.QUICKPAY_CALLBACK_URL), QuickPayCallback.as_view(), name='quickpay_callback'),
]

winda/trainings/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include

from trainings.views import (
    TrainingProviderHomeView, UserListView, UserCreateView, UserUpdateView,
    CompanyProfileDetailView, UploadBatchListView, SingleUploadCreateView,
    BulkUploadCreateView, ViewUploadView, DownloadErrorsView
)

urlpatterns = [
    url(r'^(?P<pk>\d+)/', include([
        url(r'^$', TrainingProviderHomeView.as_view(), name='home'),
        url(r'^company-profile/$', CompanyProfileDetailView.as_view(), name='company_profile'),
        url(r'^uploads/', include([
            url(r'^$', UploadBatchListView.as_view(), name='uploads'),
            url(r'^new-single/$', SingleUploadCreateView.as_view(), name='single-upload'),
            url(r'^new-bulk/$', BulkUploadCreateView.as_view(), name='bulk-upload'),
            url(r'^(?P<batch_pk>\d+)/', include([
                url(r'^$', ViewUploadView.as_view(), name='view-upload'),
                url(r'^errors.csv$', DownloadErrorsView.as_view(), name='download-errors')
            ])),
        ])),
    ])),
    url(r'^users/(?P<user_id>\d+)/', include([
        url(r'^$', UserListView.as_view(), name='users'),
        url(r'^new/$', UserCreateView.as_view(), name='user_create'),
        url(r'^(?P<pk>\d+)/edit/$', UserUpdateView.as_view(), name='user_update'),
    ]))
]

winda/users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include


urlpatterns = [

]

winda/database_admin/models.py
from django.db import models

# Create your models here.

winda/delegate/models.py
# -*- coding: utf-8 -*-
import uuid
from django.conf import settings
from django.db import models
from django.utils.translation import ugettext, ugettext_lazy as _
from django.utils import timezone

from dateutil.relativedelta import relativedelta

from common.models import TimeStampedModel, Country
from courses.models import Course
from delegate.managers import TrainingRecordManager
from trainings.models import TrainingProvider, UploadBatchRecord

User = settings.AUTH_USER_MODEL


class TrainingRecord(TimeStampedModel):

    INVALIDATED = 'invalidated'
    EXPIRED = 'expired'
    CURRENT = 'current'
    STATUSES = ()

    delegate = models.ForeignKey(User, verbose_name=_('delegate'), related_name='delegate_training_records')
    course = models.ForeignKey(Course, verbose_name=_('course'), related_name='training_records')
    country = models.ForeignKey(Country, verbose_name=_('country'))
    training_provider = models.ForeignKey(TrainingProvider, verbose_name=_('training provider'),
                                          related_name='training_provider_training_records')
    last_updated_by = models.ForeignKey(User, null=True, blank=True, related_name='%(class)s_last_updated_by')
    created_by = models.ForeignKey(User, default=settings.SYSTEM_USER_ID, related_name='%(class)s_created_by')
    completed_on = models.DateField(_('Completed On'))
    valid_from = models.DateField(_('valid from'))
    valid_until = models.DateField(_('valid until'))
    created_by_record = models.ForeignKey(UploadBatchRecord, verbose_name=_('created by record'),
                                          related_name='created_by_record')
    invalidated_at = models.DateTimeField(_('invalidated at'), null=True, blank=True)
    invalidated_by = models.ForeignKey(User, null=True, blank=True, related_name='%(class)s_invalidated_by')
    invalidated_by_record = models.ForeignKey(UploadBatchRecord, verbose_name=_('invalidated by record'),
                                              related_name='invalidated_by_record', blank=True, null=True)

    objects = TrainingRecordManager()

    class Meta:
        verbose_name = _('Training Record')
        verbose_name_plural = _('Training Records')
        index_together = (
            ('delegate', 'course', 'completed_on', 'invalidated_at'),
        )

    def __str__(self):
        return self.delegate.username

    @staticmethod
    def get_training_record_status(obj):
        icons = {
            'red': 'icon-ic_status_rectangle',
            'yellow': 'icon-ic_status_triangle',
            'green': 'icon-ic_status_circle'
        }
        if obj.invalidated_at:
            return TrainingRecord.INVALIDATED, icons.get('red')
        if obj.valid_until < timezone.now().date():
            return TrainingRecord.EXPIRED, icons.get('red')
        if obj.valid_until < (timezone.now() + relativedelta(months=settings.EXPIRING_TRAINING_RECORD_MONTHS)).date():
            return TrainingRecord.CURRENT, icons.get('yellow')
        return TrainingRecord.CURRENT, icons.get('green')

    def get_status(self):
        if self.id:
            return TrainingRecord.get_training_record_status(self)
        return ugettext('No records')

    def get_status_display(self):
        status, icon_class = self.get_status()
        return '<span class="{0}"></span>{1}'.format(icon_class, status.title())

    @staticmethod
    def get_course_status(current=None, expired=None, invalidated=None, valid_until=None):
        icons = {
            'red': 'icon-ic_status_rectangle',
            'yellow': 'icon-ic_status_triangle',
            'green': 'icon-ic_status_circle'
        }
        if current:
            return valid_until, icons.get('green')
        if expired:
            return valid_until, icons.get('yellow')
        if invalidated:
            return ugettext('Not valid'), icons.get('red')
        return ugettext('Not taken'), icons.get('red')


def certificate_file_path(instance, filename):
    return '/'.join(map(str, [settings.AWS_STORAGE_PREFIX, 'certificates/delegate',
                              instance.created.strftime('%Y-%m'), uuid.uuid4(), filename]))


class DelegateCertificate(TimeStampedModel):

    certificate_code = models.UUIDField(default=uuid.uuid4, editable=False)
    certificate_file = models.FileField(_('certificate file'), upload_to=certificate_file_path, max_length=255)
    delegate = models.ForeignKey(User, verbose_name=_('delegate'), related_name='delegate_certificates')
    created_by = models.ForeignKey(User, default=settings.SYSTEM_USER_ID, related_name='%(class)s_created_by')

    class Meta:
        verbose_name = _('Delegate Certificate')
        verbose_name_plural = _('Delegate Certificates')

    def __str__(self):
        return 'Certificate: {0}'.format(self.certificate_code)

    def get_certificate_url(self):
        return self.certificate_file.url if self.certificate_file else ''


class Search(TimeStampedModel):
    created_by = models.ForeignKey(User, related_name='%(class)s_created_by')
    delegate = models.ForeignKey(User, verbose_name=_('delegate'), related_name='search')

    class Meta:
        verbose_name = _('Search')
        verbose_name_plural = _('Searches')

    def __str__(self):
        return self.delegate.username

winda/organization/models.py
from django.db import models

# Create your models here.

winda/core/forms.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.contrib.auth import get_user_model
from django import forms
import reversion


class ModelForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        if self.request and self.request.user and self.request.user.is_authenticated():
            if self.instance.pk is None:
                self.instance.created_by = self.request.user
            else:
                self.instance.last_updated_by = self.request.user
        if reversion.is_active():
            if not reversion.get_user():
                system_user = get_user_model().objects.get(pk=settings.SYSTEM_USER_ID)
                reversion.set_user(system_user)
            if not self.instance.pk:
                reversion.set_comment('Added')
            elif self.changed_data:
                reversion.set_comment('Changed {}.'.format(', '.join(self.changed_data)))
        return super().save(commit)

winda/core/views.py
# -*- coding: utf-8 -*-
from django.views import generic
from reversion.views import RevisionMixin

class CreateView(RevisionMixin, generic.CreateView):
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


class UpdateView(RevisionMixin, generic.UpdateView):
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

winda/templates/trainings/base.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% blocktrans %}Winda Training Provider{% endblocktrans %}{% endblock title %}

winda/templates/trainings/company_profile.html
    {% extends "trainings/base.html" %}
{% load i18n %}

{% block title %}{{ block.super }} - {% trans 'company profile' %}{% endblock title %}

{% block content %}
    <h2 class="text-center">{{ training_provider.name }}</h2>
<div class="row">
    <div class="col-lg-4">
        <div class="row">
            <div class="col-lg-12 col-md-6">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <dl class="dl-horizontal">
                            <dt>{% trans 'create balance'|title %}</dt>
                            <dd>{{ training_provider.current_credit_balance }}</dd>
                            <dt>{% trans 'draft upload'|title %}</dt>
                            <dd>{{ training_provider.draft_upload_count }}</dd>
                        </dl>
                    </div>
                </div>
            </div>
            <div class="col-lg-12 col-md-6">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <dl class="dl-horizontal">
                            <dt>{% trans 'name'|title %}</dt>
                            <dd>{{ training_provider.name }}</dd>
                            {% if training_provider.country %}
                                <dt>{% trans 'country'|title %}</dt>
                                <dd>{{ training_provider.country.name }}</dd>
                            {% endif %}
                            {% if training_provider.address_1 %}
                                <dt>{% trans 'street address line 1'|title %}</dt>
                                <dd>{{ training_provider.address_1 }}</dd>
                            {% endif %}
                            {% if training_provider.address_2 %}
                                <dt>{% trans 'street address line 2'|title %}</dt>
                                <dd>{{ training_provider.address_2 }}</dd>
                            {% endif %}
                            {% if training_provider.city %}
                                <dt>{% trans 'city'|title %}</dt>
                                <dd>{{ training_provider.city }}</dd>
                            {% endif %}
                            {% if training_provider.postal_code %}
                                <dt>{% trans 'postal code'|title %}</dt>
                                <dd>{{ training_provider.postal_code }}</dd>
                            {% endif %}
                        </dl>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-8">

        <div class="panel panel-default">
          <div class="panel-body">
            <h3>{% trans 'accredited provider of course'|title %}</h3>
            <table class="datatables-simple display responsive nowrap dataTable no-footer dtr-inline" cellspacing="0" width="100%">
                <thead><tr>
                    <th></th>
                    <th>{% trans 'code'|title  %}</th>
                    <th>{% trans 'course title'|title  %}</th>
                    <th>{% trans 'valid from'|title  %}</th>
                    <th>{% trans 'valid until'|title  %}</th>
                </tr></thead>
                <tbody>
                {% for course_provider in course_providers %}
                    <tr>
                    <td></td>
                    <td>{{ course_provider.course.code }}</td>
                    <td>{{ course_provider.course.title }}</td>
                    <td>{{ course_provider.valid_from }}</td>
                    <td>{{ course_provider.valid_until }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
          </div>
        </div>

        <div class="panel panel-default">
          <div class="panel-body">
            <h3>{% trans 'certificates'|title %}</h3>
            <table class="datatables-simple display responsive nowrap dataTable no-footer dtr-inline" cellspacing="0" width="100%">
                <thead><tr>
                    <th></th>
                    <th>{% trans 'certificate number'|title  %}</th>
                    <th>{% trans 'valid from'|title  %}</th>
                    <th>{% trans 'valid until'|title  %}</th>
                </tr></thead>
                <tbody>
                {% for certificate in certificates %}
                    <tr>
                    <td></td>
                    <td>{{ certificate.certificate_number }}</td>
                    <td>{{ certificate.valid_from }}</td>
                    <td>{{ certificate.valid_until }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
          </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block breadcrumb %}
    {{ block.super }}
    {% if request.user.is_database_admin %}
        <li><a href="{% url 'database_admin:training_providers' %}">{% trans 'training providers'|title %}</a></li>
        <li><a href="{% url 'database_admin:training_provider_detail' training_provider.pk %}">{{ training_provider.name|title }}</a></li>
    {% endif %}
    <li>{% trans 'company profile'|title %}</li>
{% endblock %}

winda/templates/trainings/home.html
{% extends "trainings/base.html" %}
{% load i18n %}

{% block title %}{% blocktrans %}Winda Training Provider{% endblocktrans %}{% endblock title %}

{% block content %}
<ul class="list-menu-home">
    <li>
        <a href="{% url 'training_provider:uploads' pk=user.training_provider.pk %}">
           <figure>
                <div class="icon-wrapper"><span class="icon icon-ic_titles_uploads"></span></div>
                <figcaption>
                    <h4>{% trans 'Uploads' %}</h4>
                    <small>{% trans 'View previously uploaded training records and upload new training records of Delegates who have completed a GWO Training Module.' %}</small>
                </figcaption>
            </figure>
        </a>
    </li>
    <li>
        <a href="{% url 'credit' user.pk %}">
           <figure>
                <div class="icon-wrapper"><span class="icon icon-ic_titles_credits"></span></div>
                <figcaption>
                    <h4>{% trans 'Credits' %}</h4>
                    <small>{% trans 'Purchase credits which you can use to upload records on Delegates. You can also view your orders and transactions.' %}</small>
                </figcaption>
            </figure>
        </a>
    </li>
    <li>
        <a href="{% url 'organization:search' %}">
           <figure>
                <div class="icon-wrapper"><span class="icon icon-ic_titles_search_training_record"></span></div>
                <figcaption>
                    <h4>{% trans 'Search Training Records' %}</h4>
                    <small>{% trans 'Search records of trained individuals to verify their current training status. You can search for up to 100 individuals at a time if they have provided you with their WINDA ID.' %}</small>
                </figcaption>
            </figure>
        </a>
    </li>
    <li>
        <a href="{% url 'training_provider:company_profile' object.pk %}">
           <figure>
                <div class="icon-wrapper"><span class="icon icon-ic_titles_view_profile"></span></div>
                <figcaption>
                    <h4>{% trans 'Company Profile' %}</h4>
                    <small>{% trans 'View your company profile and information registered in WINDA.' %}</small>
                </figcaption>
            </figure>
        </a>
    </li>
</ul>
{% endblock content %}

{% block breadcrumb %}{% endblock %}

winda/templates/trainings/upload_batch_list.html
{% extends "trainings/base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block content %}
    <h2 class="text-center">{{provider.name}} - {% trans 'Uploads' %}</h2>
    <p>{% trans 'View all uploads and their status in the overview below. To view the details of the records, click on the description of the relevant upload. To perform a new upload to WINDA, you can choose to either upload up to 100 records at once by clicking “New Bulk Upload” or you can upload single records by clicking “New Single Upload”.' %}</p>
    <p>
        <a href="{% url 'training_provider:bulk-upload' pk=provider.pk %}" class="btn btn-default">{% trans 'New bulk upload' %}</a>
        <a href="{% url 'training_provider:single-upload' pk=provider.pk %}" class="btn btn-default">{% trans 'New single upload' %}</a>
    </p>
    <table id="upload_batch_list" class="display responsive nowrap dataTable no-footer dtr-inline">
        <thead><tr>
            {% for title in form.FIELDS.values %}
                <th>{{ title|title }}</th>
            {% endfor %}
        </tr></thead>
        <tbody></tbody>
    </table>
{% endblock %}

{% block breadcrumb %}
    {{ block.super }}
    {% if user.is_database_admin %}
        <li><a href="{% url 'database_admin:training_providers' %}">{% trans 'training providers'|title %}</a></li>
        <li><a href="{% url 'database_admin:training_provider_detail' provider.pk %}">{{ provider.name|title }}</a></li>
    {% endif %}
    <li>{% trans 'Uploads' %}</li>
{% endblock %}

winda/templates/trainings/users.html
{% extends "trainings/base.html" %}
{% load i18n %}

{% block title %}{{ block.super }} - {% trans 'users'|title %}{% endblock title %}

{% block content %}
    <div class="row">
        <h2 class="text-center">{{ user.training_provider.name }} - {% trans 'Users' %}</h2>
        <p>
            <a href="{% url 'training_provider:user_create' user.pk %}" class="btn btn-default">{% trans 'create new user'|capfirst %}</a>
        </p>

        <table id="training_provider_user" class="display responsive nowrap dataTable no-footer dtr-inline">
            <thead><tr>
                {% for title in form.FIELDS.values %}
                    <th>{{ title|title }}</th>
                {% endfor %}
            </tr></thead>
            <tbody></tbody>
        </table>
    </div>
{% endblock content %}

{% block breadcrumb %}
    {{ block.super }}
    <li>{% trans 'users'|title %}</li>
{% endblock %}

winda/templates/trainings/view_upload_template.html
{% extends "trainings/base.html" %}
{% load i18n %}
{% load widget_tweaks %}
{% load staticfiles %}

{% block content %}
<div class="wrapper-form">
    <h2 class="text-center">{{provider.name}} - {% trans 'Upload #' %}{{object.id}}</h2>
    <p class="text-center">{% trans 'See details of this credit transaction below' %}</p>
    <p class="text-center">
        <a href="{% url 'training_provider:download-errors' pk=provider.pk batch_pk=object.pk %}" class="text-center">{% trans 'Download file with error details' %}</a>
    </p>

    <div class="panel panel-default">
        <div class="panel-body">
            <dl class="dl-horizontal dl-center">
                <dt>{% trans 'Description' %}</dt>
                  <dd>{{object.description}}</dd>
                <dt>{% trans 'Status' %}</dt>
                  <dd>{{object.get_status_display}}</dd>
                <dt>{% trans 'Total Records' %}</dt>
                  <dd>{{object.total_records}}</dd>
                <dt>{% trans 'Valid Records' %}</dt>
                  <dd>{{object.valid_records}}</dd>
                <dt>{% trans 'Duplicate Records' %}</dt>
                  <dd>{{object.duplicate_records}}</dd>
                <dt>{% trans 'Error Records' %}</dt>
                  <dd>{{object.error_records}}</dd>
                <dt>{% trans 'Uploaded At' %}</dt>
                  <dd>{{object.created}}</dd>
                <dt>{% trans 'Uploaded By' %}</dt>
                  <dd>{{object.created_by.get_full_name}}</dd>
            </dl>
        </div>
    </div>
    {% if object.is_draft %}
        {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">{{ form.non_field_errors }}</div>
        {% endif %}
    <div class="text-center">
        <form class='purchase' action="" method="post">
            <button id="discard" class="btn btn-primary btn-lg text-uppercase" data-status="discarded">{% trans 'Discard' %}</button>
            <button id="purchase" class="btn btn-primary btn-lg text-uppercase" data-status="purchased">{% trans 'Purchase' %}</button>
            {% csrf_token %}
            <input type="hidden" name="status" value="purchased" />
        </form>
    </div>
    <p class="row text-center">
        {% trans 'Please wait up to 60 seconds for purchases to complete' %}
    </p>
    {% endif %}
</div>
{% endblock %}


{% block breadcrumb %}
    {{ block.super }}
    <li><a href="{% url 'training_provider:uploads' pk=provider.pk %}">{% trans 'Uploads' %}</a></li>
    <li>{% trans 'Upload #' %}{{object.id}}</li>
{% endblock %}