config/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from django.contrib.flatpages import views
from delegate.views import DelegateCertificateView


urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),
    # User management
    url(r'^', include('common.urls')),
    url(r'^', include('orders.urls')),
    url(r'^', include('registration.urls')),
    url(r'^admin/ses/', include('django_ses.urls')),
    url(r'^delegate/', include('delegate.urls', namespace='delegate')),
    url(r'^organization/', include('organization.urls', namespace='organization')),
    url(r'^training-provider/', include('trainings.urls', namespace='training_provider')),
    url(r'^database-admin/', include('database_admin.urls', namespace='database_admin')),
    url(r'^database-super-admin/', include('database_super_admin.urls', namespace='database_super_admin')),
    url(r'^certificate/(?P<certificate_code>[^/]+)$', DelegateCertificateView.as_view(), name='delegate-certificate'),
]

# flatpages
urlpatterns += [
    url(r'^about/', include([
        url(r'^$', views.flatpage, {'url': '/about/'}, name='about'),
        url(r'^terms-and-conditions/$', views.flatpage, {'url': '/terms-and-conditions/'}, name='terms'),
        url(r'^privacy-policy/$', views.flatpage, {'url': '/privacy-policy/'}, name='privacy'),
        url(r'^service-level-agreement/$', views.flatpage, {'url': '/service-level-agreement/'}, name='agreement'),
    ])),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request),
        url(r'^403/$', default_views.permission_denied),
        url(r'^404/$', default_views.page_not_found),
        url(r'^500/$', default_views.server_error),
    ]

winda/common/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from common.views import HomeView, SendEmailNotificationRedirectView, SNSCallback, ArchiveRedirectView, \
    GenerateNotificationsRedirectView

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^sns-callback/$', SNSCallback.as_view(), name='sns_callback'),
    url(r'^send-email-notification/$', SendEmailNotificationRedirectView.as_view(), name='send_email_notification'),
    url(r'^archive/$', ArchiveRedirectView.as_view(), name='archive'),
    url(r'^generate-notifications/$', GenerateNotificationsRedirectView.as_view(), name='generate_notifications'),
]

winda/delegate/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include

from .views import DelegateHomeView, DelegateProfileView, DelegateSearchView, DelegateSearchResultView, \
    DelegateGenerateCertificateView, DelegateTrainingRecordsListView

urlpatterns = [
    url(r'^search/$', DelegateSearchView.as_view(), name='search'),
    url(r'^search/(?P<delegate_id>[\w ]+)/$', DelegateSearchResultView.as_view(), name='search_result'),

    url(r'^(?P<delegate_id>[\w]+)/', include([
        url(r'^$', DelegateHomeView.as_view(), name='home'),
        url(r'^profile/$', DelegateProfileView.as_view(), name='profile'),
        url(r'^training-record/$', DelegateTrainingRecordsListView.as_view(), name='training-record'),
        url(r'^certificate/$', DelegateGenerateCertificateView.as_view(), name='generate-certificate'),
    ])),
]

winda/orders/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import url, include

from orders.views import CreditTemplateView, PurchaseCreditView, PurchaseConfirmView, OrderView, OrderDetailView, \
    EmailOrderDetailView, QuickPayCallback, OrderPaymentLinkView, TransactionView, TransactionDetailView

urlpatterns = [
    url(r'^training-provider/(?P<pk>\d+)/', include([
        url(r'^credits/$', CreditTemplateView.as_view(), name='credit'),
        url(r'^credits/purchase/$', PurchaseCreditView.as_view(), name='purchase_credit'),
        url(r'^credits/purchase-confirm/$', PurchaseConfirmView.as_view(), name='purchase_credit_confirm'),
        url(r'^orders/$', OrderView.as_view(), name='orders'),
        url(r'^orders/(?P<order_pk>\d+)/$', OrderDetailView.as_view(), name='order_detail'),
        url(r'^orders/(?P<order_pk>\d+)/email/$', EmailOrderDetailView.as_view(), name='order_email'),
        url(r'^orders/(?P<order_pk>\d+)/link/$', OrderPaymentLinkView.as_view(), name='order_link'),
        url(r'^transactions/$', TransactionView.as_view(), name='transactions'),
        url(r'^transactions/(?P<transaction_pk>\d+)/$', TransactionDetailView.as_view(), name='transaction_detail'),
    ])),

    url(r'^{}/$'.format(settings.QUICKPAY_CALLBACK_URL), QuickPayCallback.as_view(), name='quickpay_callback'),
]

winda/users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include


urlpatterns = [

]

winda/database_admin/models.py
from django.db import models

# Create your models here.

winda/delegate/models.py
# -*- coding: utf-8 -*-
import uuid
from django.conf import settings
from django.db import models
from django.utils.translation import ugettext, ugettext_lazy as _
from django.utils import timezone

from dateutil.relativedelta import relativedelta

from common.models import TimeStampedModel, Country
from courses.models import Course
from delegate.managers import TrainingRecordManager
from trainings.models import TrainingProvider, UploadBatchRecord

User = settings.AUTH_USER_MODEL


class TrainingRecord(TimeStampedModel):

    INVALIDATED = 'invalidated'
    EXPIRED = 'expired'
    CURRENT = 'current'
    STATUSES = ()

    delegate = models.ForeignKey(User, verbose_name=_('delegate'), related_name='delegate_training_records')
    course = models.ForeignKey(Course, verbose_name=_('course'), related_name='training_records')
    country = models.ForeignKey(Country, verbose_name=_('country'))
    training_provider = models.ForeignKey(TrainingProvider, verbose_name=_('training provider'),
                                          related_name='training_provider_training_records')
    last_updated_by = models.ForeignKey(User, null=True, blank=True, related_name='%(class)s_last_updated_by')
    created_by = models.ForeignKey(User, default=settings.SYSTEM_USER_ID, related_name='%(class)s_created_by')
    completed_on = models.DateField(_('Completed On'))
    valid_from = models.DateField(_('valid from'))
    valid_until = models.DateField(_('valid until'))
    created_by_record = models.ForeignKey(UploadBatchRecord, verbose_name=_('created by record'),
                                          related_name='created_by_record')
    invalidated_at = models.DateTimeField(_('invalidated at'), null=True, blank=True)
    invalidated_by = models.ForeignKey(User, null=True, blank=True, related_name='%(class)s_invalidated_by')
    invalidated_by_record = models.ForeignKey(UploadBatchRecord, verbose_name=_('invalidated by record'),
                                              related_name='invalidated_by_record', blank=True, null=True)

    objects = TrainingRecordManager()

    class Meta:
        verbose_name = _('Training Record')
        verbose_name_plural = _('Training Records')
        index_together = (
            ('delegate', 'course', 'completed_on', 'invalidated_at'),
        )

    def __str__(self):
        return self.delegate.username

    @staticmethod
    def get_training_record_status(obj):
        icons = {
            'red': 'icon-ic_status_rectangle',
            'yellow': 'icon-ic_status_triangle',
            'green': 'icon-ic_status_circle'
        }
        if obj.invalidated_at:
            return TrainingRecord.INVALIDATED, icons.get('red')
        if obj.valid_until < timezone.now().date():
            return TrainingRecord.EXPIRED, icons.get('red')
        if obj.valid_until < (timezone.now() + relativedelta(months=settings.EXPIRING_TRAINING_RECORD_MONTHS)).date():
            return TrainingRecord.CURRENT, icons.get('yellow')
        return TrainingRecord.CURRENT, icons.get('green')

    def get_status(self):
        if self.id:
            return TrainingRecord.get_training_record_status(self)
        return ugettext('No records')

    def get_status_display(self):
        status, icon_class = self.get_status()
        return '<span class="{0}"></span>{1}'.format(icon_class, status.title())

    @staticmethod
    def get_course_status(current=None, expired=None, invalidated=None, valid_until=None):
        icons = {
            'red': 'icon-ic_status_rectangle',
            'yellow': 'icon-ic_status_triangle',
            'green': 'icon-ic_status_circle'
        }
        if current:
            return valid_until, icons.get('green')
        if expired:
            return valid_until, icons.get('yellow')
        if invalidated:
            return ugettext('Not valid'), icons.get('red')
        return ugettext('Not taken'), icons.get('red')


def certificate_file_path(instance, filename):
    return '/'.join(map(str, [settings.AWS_STORAGE_PREFIX, 'certificates/delegate',
                              instance.created.strftime('%Y-%m'), uuid.uuid4(), filename]))


class DelegateCertificate(TimeStampedModel):

    certificate_code = models.UUIDField(default=uuid.uuid4, editable=False)
    certificate_file = models.FileField(_('certificate file'), upload_to=certificate_file_path, max_length=255)
    delegate = models.ForeignKey(User, verbose_name=_('delegate'), related_name='delegate_certificates')
    created_by = models.ForeignKey(User, default=settings.SYSTEM_USER_ID, related_name='%(class)s_created_by')

    class Meta:
        verbose_name = _('Delegate Certificate')
        verbose_name_plural = _('Delegate Certificates')

    def __str__(self):
        return 'Certificate: {0}'.format(self.certificate_code)

    def get_certificate_url(self):
        return self.certificate_file.url if self.certificate_file else ''


class Search(TimeStampedModel):
    created_by = models.ForeignKey(User, related_name='%(class)s_created_by')
    delegate = models.ForeignKey(User, verbose_name=_('delegate'), related_name='search')

    class Meta:
        verbose_name = _('Search')
        verbose_name_plural = _('Searches')

    def __str__(self):
        return self.delegate.username

winda/organization/models.py
from django.db import models

# Create your models here.

winda/core/forms.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.contrib.auth import get_user_model
from django import forms
import reversion


class ModelForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        if self.request and self.request.user and self.request.user.is_authenticated():
            if self.instance.pk is None:
                self.instance.created_by = self.request.user
            else:
                self.instance.last_updated_by = self.request.user
        if reversion.is_active():
            if not reversion.get_user():
                system_user = get_user_model().objects.get(pk=settings.SYSTEM_USER_ID)
                reversion.set_user(system_user)
            if not self.instance.pk:
                reversion.set_comment('Added')
            elif self.changed_data:
                reversion.set_comment('Changed {}.'.format(', '.join(self.changed_data)))
        return super().save(commit)

winda/courses/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.utils.translation import ugettext_lazy as _

from core.forms import ModelForm
from courses.models import Course


class AdminCourseCreateForm(ModelForm):

    error_messages = {
        'duplicate_code': _('Course with the same code already exists')
    }

    class Meta:
        model = Course
        fields = ('code', 'title', 'course_type', 'refresher_for_course', 'require_existing_training_record',
                  'validity_months')

    def clean_code(self):
        code = self.cleaned_data.get('code')
        if code:
            code = code.strip().upper()
            courses = Course.objects.filter(code=code)
            if self.instance:
                courses = courses.exclude(id=self.instance.id)
            if courses.exists():
                raise forms.ValidationError(self.error_messages['duplicate_code'])
            self.cleaned_data['code'] = code
        return code

    def clean(self):
        course_type = self.cleaned_data.get('course_type')
        refresher_for_course = self.cleaned_data.get('refresher_for_course')
        if course_type == Course.REFRESHER and not refresher_for_course:
            raise forms.ValidationError(
                _('Refresher for course field is required for Refresher course'),
                code='refresher_for_course_required')


class AdminCourseEditForm(AdminCourseCreateForm):

    class Meta:
        model = Course
        fields = ('title', 'course_type', 'refresher_for_course', 'require_existing_training_record',
                  'validity_months')

    def __init__(self, *args, **kwargs):
        super(AdminCourseEditForm, self).__init__(*args, **kwargs)

winda/common/views.py
# -*- coding: utf-8 -*-
import logging
from braces.views import JSONResponseMixin

from django.contrib.auth import get_user_model
from django.core.management import call_command
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.shortcuts import redirect
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.defaults import page_not_found
from django.views.generic import TemplateView, RedirectView

from common.forms import EmailNotificationForm
from common.models import EmailNotification
from core.views import CreateView


logger = logging.getLogger('sentry.errors')


class HomeView(TemplateView):
    template_name = 'common/home.html'

    home_mapping = {
        get_user_model().DELEGATE: ('delegate:home', 'delegate_id', 'delegate_id'),
        get_user_model().ORGANIZATION: ('organization:home', 'pk', 'pk'),
        get_user_model().TRAINING_PROVIDER: ('training_provider:home', 'pk', 'training_provider_id'),
        get_user_model().TRAINING_PROVIDER_ADMIN: ('training_provider:home', 'pk', 'training_provider_id'),
        get_user_model().DATABASE_ADMIN: ('database_admin:home', '', ''),
        get_user_model().DATABASE_SUPER_ADMIN: ('database_super_admin:home', '', ''),
    }

    def dispatch(self, request, *args, **kwargs):
        if request.user and request.user.is_authenticated():
            values = self.home_mapping.get(request.user.role)
            if values:
                url, slug_name, field = values
                kwargs = {slug_name: getattr(request.user, field)} if slug_name else {}
                return redirect(reverse(url, kwargs=kwargs))

        return super(HomeView, self).dispatch(request, *args, **kwargs)


class SendEmailNotificationRedirectView(RedirectView):
    permanent = False
    pattern_name = 'admin:common_emailnotification_changelist'

    def get(self, request, *args, **kwargs):
        call_command('deliveremails')
        return super().get(request, *args, **kwargs)


class ArchiveRedirectView(RedirectView):
    permanent = False
    pattern_name = 'admin:users_user_changelist'

    def get(self, request, *args, **kwargs):
        call_command('archive')
        return super().get(request, *args, **kwargs)


class GenerateNotificationsRedirectView(RedirectView):
    permanent = False
    pattern_name = 'admin:common_emailnotification_changelist'

    def get(self, request, *args, **kwargs):
        call_command('generatenotifications', date=request.GET.get('date', ''))
        return super().get(request, *args, **kwargs)


class SNSCallback(JSONResponseMixin, CreateView):
    http_method_names = ['post']
    model = EmailNotification
    form_class = EmailNotificationForm

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.save()
        return HttpResponse(status=200)

    def form_invalid(self, form):
        logger.error('{} - {}'.format(form.errors.as_text(), self.request.body))
        return self.render_json_response(form.errors, status=400)


def page_not_found_view(request, template_name='404.html', **kwargs):
    return page_not_found(request, template_name)

winda/core/views.py
# -*- coding: utf-8 -*-
from django.views import generic
from reversion.views import RevisionMixin

class CreateView(RevisionMixin, generic.CreateView):
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


class UpdateView(RevisionMixin, generic.UpdateView):
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

winda/templates/delegate/certificate_template.html
{% load i18n %}
<!DOCTYPE html>
<html>
<head>
    <title>{% trans 'Delegate Certificate' %}</title>
    <style type="text/css">
        .wrapper {
          font-family: Arial, Helvetica, sans-serif;
          margin: 0 auto;
          width: 100%;
        }
       .text-center {
          text-align: center;
       }
        table {
          border-collapse: collapse;
          border-right: 1px solid;
          border-top: 1px solid;
          border-bottom: 1px solid;
          width: 100%;
        }
        tr:nth-child(odd) {background: #eee}
        thead td {
          background: #ccc;
        }
        td {
          font-size: 12px;
          border-top: none;
          border-bottom: none;
          border-width: 1px;
          border-right: none;
          border-left: 1px solid;
        }
      </style>
</head>
<body>

<div class="wrapper">
    <div class="text-center">
        <img src="images/sample_image.jpg" width='100' height='100'/>
        <h2>{% trans 'Global Wind Organization' %}
        <br>{% trans 'WINDA Delegate Training Certificate' %}</h2>
        <p><strong>{% trans 'Winda ID' %}</strong><br>
            <span>{{delegate.delegate_id}}</span></p>
        <p><strong>{% trans 'Delegate Name' %}</strong><br>
            <span>{{delegate.get_full_name}}</span></p>
    </div>
    <table cellpadding="5">
        <caption><p class="text-center">{% trans 'Training certificate generated on' %} {% now 'DATETIME_FORMAT' %}</p></caption>
        <thead>
            <tr>
                <td>{% trans 'Course Title' %}</td>
                <td>{% trans 'Course Code' %}</td>
                <td>{% trans 'Training Provider' %}</td>
                <td>{% trans 'Country' %}</td>
                <td>{% trans 'Completion Date' %}</td>
                <td>{% trans 'Valid From' %}</td>
                <td>{% trans 'Valid Until' %}</td>
                <td>{% trans 'Status' %}</td>
            </tr>
        </thead>
        <tbody>
        {% for record in training_records %}
            <tr>
                <td>{{record.course.title}}</td>
                <td>{{record.course.code}}</td>
                <td>{{record.training_provider.name}}</td>
                <td>{{record.country.name}}</td>
                <td>{{record.completed_on|date:'DATE_FORMAT'}}</td>
                <td>{{record.valid_from|date:'DATE_FORMAT'}}</td>
                <td>{{record.valid_until|date:'DATE_FORMAT'}}</td>
                <td>{{record.get_status_display|safe}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
  <br><br><br><br>
    <table cellpadding="5">
        <thead>
            <tr>
                <td>{% trans 'Training Provider' %}</td>
                <td>{% trans 'Country' %}</td>
                <td>{% trans 'Address' %}</td>
            </tr>
        </thead>
        <tbody>
        {% for provider in training_providers %}
            <tr>
                <td>{{provider.name}}</td>
                <td>{{provider.country.name}}</td>
                <td>{{provider.address_1}}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <br><br>
    <p style="font-size: 13px;">
        <strong>{% trans 'Certificate Code' %}:</strong> {{certificate.certificate_code}}<br>
        <strong>{% trans 'Certificate URL' %}:</strong> <a href="{{certificate_url}}">{{certificate_url}}</a>
    </p>
    <p style="font-size: 12px;">
        {% blocktrans %}
            Verify the current training status of delegates by searching WINDA at <a href="{{domain}}">{{domain}}</a>
        {% endblocktrans%}
    </p>
  </div>


</body>
</html>

winda/templates/delegate/generate_certificate.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}Winda Delegate{% endblock title %}
{% block content %}
<div class="row">

</div>
<div class="row">
{% if training_records.count %}
    <p class="alert alert-info">{% trans 'Something went wrong try again later.' %}</p>
{% else %}
    <p class="alert alert-info">{% trans 'No current training records exist for this delegate.' %}</p>
{% endif %}
</div>
{% endblock content %}

{% block breadcrumb %}
    {{ block.super }}
    <li>{% trans 'Delegate Certificate' %}</li>
{% endblock %}

winda/templates/delegate/home.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}Winda Delegate{% endblock title %}
{% block content %}
<ul class="list-menu-home">
    <li>
        <a href="{% url 'delegate:training-record' delegate_id=object.delegate_id %}">
           <figure>
                <div class="icon-wrapper"><span class="icon icon-ic_titles_training_record"></span></div>
                <figcaption>
                    <h4>{% trans 'Training Record' %}</h4>
                    <small>{% trans 'View and print your GWO training records that has been added to your profile by your Training Provider. Please ensure that your training records are always valid as you will not be able to attend a refresher training course with an expired training record.' %}</small>
                </figcaption>
            </figure>
        </a>
    </li>
    <li>
        <a href="{% url 'delegate:profile' delegate_id=object.delegate_id %}">
           <figure>
                <div class="icon-wrapper"><span class="icon icon-ic_titles_edit_profile"></span></div>
                <figcaption>
                    <h4>{% trans 'My Profile' %}</h4>
                    <small>{% trans 'View your personal information that you have registered in WINDA. You can also edit or change your email address.' %}</small>
                </figcaption>
            </figure>
        </a>
    </li>
    <li>
        <a href="{% url 'delegate:search' %}">
           <figure>
                <div class="icon-wrapper"><span class="icon icon-ic_titles_search"></span></div>
                <figcaption>
                    <h4>{% trans 'Search' %}</h4>
                    <small>{% trans 'Search for an individual’s training record. You will need their WINDA ID in order to use the search function.' %}</small>
                </figcaption>
            </figure>
        </a>
    </li>
</ul>
{% endblock content %}

{% block breadcrumb %}{% endblock %}

winda/templates/delegate/profile.html
{% extends "base.html" %}
{% load i18n %}
{% load widget_tweaks %}

{% block title %}Winda Delegate{% endblock title %}
{% block content %}
<div class="wrapper-form">
<h2 class="text-center">{% trans 'My profile' %}</h2>
<p>{% trans 'This is the information that you have registered in WINDA. You are not able to change your name. If you have changed your email address, please update it in the field below.' %}</p>
<form method="POST" action="#" class="form-horizontal">
    {% csrf_token %}
    <fieldset>
      <div class="form-group row">
            <label class="col-sm-3 control-label text-right" form="{{ form.delegate_id.id_for_label }}">{{ form.delegate_id.label|capfirst }}</label>
            <div class="col-sm-9">
                {% render_field form.delegate_id class='form-control no-binput' placeholder=form.delegate_id.label|capfirst %}
                <div class="errors">{{ form.delegate_id.errors }}</div>
            </div>
      </div>
      <div class="form-group row">
            <label class="col-sm-3 control-label text-right" form="{{ form.first_name.id_for_label }}">{{ form.first_name.label|capfirst }}</label>
            <div class="col-sm-9">
                {% render_field form.first_name class='form-control no-binput' placeholder=form.first_name.label|capfirst %}
                <div class="errors">{{ form.first_name.errors }}</div>
            </div>
      </div>
      <div class="form-group row">
            <label class="col-sm-3 control-label text-right" form="{{ form.last_name.id_for_label }}">{{ form.last_name.label|capfirst }}</label>
            <div class="col-sm-9">
                {% render_field form.last_name class='form-control no-binput' placeholder=form.last_name.label|capfirst %}
                <div class="errors">{{ form.last_name.errors }}</div>
            </div>
      </div>
      <div class="form-group row">
            <label class="col-sm-3 control-label text-right" form="{{ form.email.id_for_label }}">{{ form.email.label|capfirst }}</label>
            <div class="col-sm-9">
                {% render_field form.email class='form-control' placeholder=form.email.label|capfirst %}
                <div class="errors">{{ form.email.errors }}</div>
            </div>
      </div>
      <div class="form-group row">
            <label class="col-sm-3 control-label text-right" form="{{ form.timezone.id_for_label }}">{{ form.timezone.label|capfirst }}</label>
            <div class="col-sm-9">
                {% render_field form.timezone class='form-control' placeholder=form.timezone.label|capfirst %}
                <div class="errors">{{ form.timezone.errors }}</div>
            </div>
      </div>
    </fieldset>
    <div class="text-center">
        <button type="submit" class="btn btn-primary btn-lg text-uppercase">{% trans 'Update Profile' %}</button>
    </div>
</form>
</div>
{% endblock content %}

{% block breadcrumb %}
    {{ block.super }}
    <li>{% trans 'My Profile' %}</li>
{% endblock %}

winda/templates/delegate/search.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block title %}{% trans "Search" %}{% if user.is_organization %} {% trans 'Training Records' %}{% endif %}{% endblock title %}
{% block content %}
<div class="wrapper-form">
    <p>{% trans 'If an individual has provided you with their WINDA ID, you can verify their current training status by entering the ID in the field below.' %}</p>
    <form method="POST" action="#" class="form-horizontal">
        {% csrf_token %}
        <fieldset>
            <div class="form-group row">
                <label class="col-sm-3 control-label text-right" form="{{ form.delegate_id.id_for_label }}">{{ form.delegate_id.label|capfirst }}</label>
                <div class="col-sm-9">
                    {% render_field form.delegate_id class='form-control' placeholder=form.delegate_id.label|capfirst %}
                    <div class="errors">{{ form.delegate_id.errors }}</div>
                </div>
            </div>
        </fieldset>
        <div class="text-center">
            <button class="btn btn-primary btn-lg text-uppercase" type="submit">{% trans "Search" %}</button>
        </div>
    </form>
</div>
{% endblock content %}

{% block breadcrumb %}
    {{ block.super }}
    <li>{% trans "Search" %}{% if user.is_organization %} {% trans 'Training Records' %}{% endif %}</li>
{% endblock breadcrumb %}

winda/templates/delegate/search_result.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block title %}{% trans "Search" %}{% endblock title %}

{% block breadcrumb %}
    {{ block.super }}
    <li><a href="{% url 'delegate:search' %}">{% trans 'Search' %}</a></li>
    <li>{% trans 'Winda ID' %} {{ delegate_id }}</li>
{% endblock %}

{% block content %}
    <h4 class="text-center">{% trans 'Search results show current training records only.' %}</h4>
    <h4 class="text-center">{% trans 'Search results valid as at' %} {% now 'DATETIME_FORMAT' %}.</h4>
    <table id="delegate-search-result" class="display responsive nowrap dataTable no-footer dtr-inline">
        <thead><tr>
            {% for title in form.FIELDS.values %}
                <th>{{ title }}</th>
            {% endfor %}
        </tr></thead>
        <tbody></tbody>
    </table>
{% endblock content %}

winda/templates/delegate/training_records_list.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block title %}{% blocktrans %}Winda Delegate{% endblocktrans %}{% endblock title %}

{% block breadcrumb %}
    {{ block.super }}
    <li>{% trans 'Training Record' %}</li>
{% endblock %}

{% block content %}
    <h2 class="text-center">{% trans 'Training Record' %}</h2>
    <div class="text-center">
        <a href="{% url 'delegate:generate-certificate' delegate_id=user.delegate_id %}" class="btn btn-default download-btn">{% trans 'Download training certificate'|capfirst %}</a>
    </div>
    <h3 class="text-center">{% trans 'Training record current as at' %} {% now 'DATETIME_FORMAT' %}</h3>
    <table id="training_record" class="display responsive nowrap dataTable no-footer dtr-inline">
        <thead><tr>
            {% for title in form.FIELDS.values %}
                <th>{{ title|title }}</th>
            {% endfor %}
        </tr></thead>
        <tbody></tbody>
    </table>
{% endblock content %}